name: Deploy static HTML frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: write
      deployments: write
      packages: write
      pull-requests: write
      repository-projects: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static files for deployment
        run: zip release.zip index.html

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloudindustry-frontend'
          package: release.zip
