name: Build Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Verify HTML file
      run: |
        test -f index.html && echo "HTML file found" || echo "HTML file not found"
